site_name: RenderCV
site_description: LaTeX CV generator engine from a YAML input file.
site_author: Sina Atalay
copyright: Copyright &copy; 2023 - 2024 Sina Atalay
site_url: https://docs.rendercv.com
repo_url: https://github.com/sinaatalay/rendercv
repo_name: sinaatalay/rendercv
edit_uri: edit/main/docs/

theme:
  name: material
  language: en
  custom_dir: docs/overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - content.code.copy # the copy-to-clipboard buttons for code blocks
    - content.action.view # view source button for pages
    - content.action.edit # view source button for pages
    - navigation.footer # the previous and next buttons in the footer
    - navigation.indexes # allow mother pages to have their own index pages
    # - navigation.tabs # render classical type of navbar at top
    - navigation.instant # instant navigation for faster page loads
    - navigation.instant.prefetch # prefetch pages for instant navigation
    - navigation.instant.progress # show progress bar for instant navigation
    - navigation.top # back to top button
    - search.highlight # highlight search results after going to a page
    - search.suggest # show search suggestions while typing
    - search.share # share search results with others
    - toc.follow # if toc sidebar doesn't fit, scroll to the active heading
    - content.code.annotate # allow annotations in code blocks
    - content.tabs.link # switch all the content tabs to the same label

nav:
  - Overview: index.md
  - User Guide:
      - User Guide: user_guide/index.md
      - Structure of the YAML input file: user_guide/structure_of_the_yaml_input_file.md
      - CLI: user_guide/cli.md
      - FAQ: user_guide/faq.md
  - Developer Guide:
      - Developer Guide: developer_guide/index.md
      - Writing Documentation: developer_guide/writing_documentation.md
      - Testing: developer_guide/testing.md
      - FAQ: developer_guide/faq.md
  - API Reference:
      - Reference: reference/index.md
      - cli:
          - cli: reference/cli/index.md
          - commands.py: reference/cli/commands.md
          - printer.py: reference/cli/printer.md
          - utilities.py: reference/cli/utilities.md
      - data:
          - data: reference/data/index.md
          - models:
              - models: reference/data/models/index.md
              - base.py: reference/data/models/base.md
              - computers.py: reference/data/models/computers.md
              - entry_types.py: reference/data/models/entry_types.md
              - curriculum_vitae.py: reference/data/models/curriculum_vitae.md
              - design.py: reference/data/models/design.md
              - locale_catalog.py: reference/data/models/locale_catalog.md
              - rendercv_settings.py: reference/data/models/rendercv_settings.md
              - rendercv_data_model.py: reference/data/models/rendercv_data_model.md
          - generator.py: reference/data/generator.md
          - reader.py: reference/data/reader.md
      - renderer:
          - renderer: reference/renderer/index.md
          - renderer.py: reference/renderer/renderer.md
          - templater.py: reference/renderer/templater.md
      - themes:
          - themes: reference/themes/index.md
          - common_options.py: reference/themes/common_options.md
          - classic: reference/themes/classic.md
          - engineeringresumes: reference/themes/engineeringresumes.md
          - sb2nov: reference/themes/sb2nov.md
          - moderncv: reference/themes/moderncv.md
  - Changelog: changelog.md

markdown_extensions:
  # see https://facelessuser.github.io/pymdown-extensions/extensions/inlinehilite/ for more pymdownx info
  - extra # Enable the Markdown Extra extensions
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: # content tabs
      alternate_style: true
  - toc:
      permalink: true
      title: Page contents
  - admonition # blocks like note, warning, tip, etc.

plugins:
  - search
  - macros: # mkdocs-macros-plugin
      module_name: docs/update_entry_figures
  - mkdocstrings:
      handlers:
        python:
          paths:
            - rendercv
          options:
            members_order: source
            show_bases: true
            docstring_section_style: list
            docstring_style: google

extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - assets/stylesheets/rendercv.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  analytics:
    provider: google
    property: G-7D7Y8D5Q4W
